micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        signatures:
          jwks:
            oauth:
              url: '${JWKS_URI}'