micronaut:
  security:
    enabled: true
    token:
      jwt:
        bearer:
          enabled: true
    oauth2:
      enabled: '${OIDC_ENABLED:true}'
      clients:
        oidc:
          client-secret: '${OIDC_CLIENT_SECRET:changeme}'
          client-id: '${OIDC_CLIENT_ID:changeme}'
          openid:
            issuer: '${OIDC_ISSUER_URI:changeme}'
          scopes: '${OIDC_SCOPES:`openid profile`}'
