version: "3"
services:

  qtz:
    image: com.github.stephenott/qtz
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - qtz

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.3
    container_name: elasticsearch
    networks:
      - qtz
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    stop_grace_period: 5m
    ports:
      - '9200:9200'
    volumes:
    - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  zeebe:
    image: camunda/zeebe:0.20.0
    container_name: zeebe
    networks:
      - qtz
    #    environment:
    #      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    depends_on:
      - elasticsearch

  operate:
    image: camunda/operate:1.0.0
    container_name: operate
    networks:
      - qtz
    ports:
      - "8082:8080"
    volumes:
      - ./operate/application.yml:/usr/local/operate/config/application.yml
    depends_on:
      - zeebe
  
networks:
  qtz: